FROM node:erbium-slim

# change working directory
WORKDIR /usr/src/app

RUN npm install -g typescript

RUN tsc -v

# copy app
COPY backend ./backend
COPY shared ./shared
COPY tslint.json .

# build shared
WORKDIR /usr/src/app/shared

RUN npm install

RUN npm run build

WORKDIR /usr/src/app/backend

# install dependencies
RUN npm install

RUN npm run build

EXPOSE 3030

CMD [ "npm", "start" ]
