name: Production CI/CD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  cd-backend:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: vrhood/webapp-backend

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build
        run: docker build -f Dockerfile.backend --build-arg environment=production -t ${{ env.DOCKER_IMAGE_NAME }} .
      - name: Tags
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Push
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

  cd-frontend:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: vrhood/webapp-frontend

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build
        run: docker build -f Dockerfile.frontend --build-arg environment=production -t ${{ env.DOCKER_IMAGE_NAME }} .
      - name: Tags
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Push
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest
